# yamllint disable rule:line-length
---
sudo: required
language: rust

git:
  submodules: false

matrix:
  include:

    - os: linux

    - os: osx
      osx_image: xcode8

    - os: windows

cache: cargo

script:
  - ./.travish.sh

_github_api_key: &_github_api_key
  api_key:
    secure: "rt7J8tM6aoAGikRmoE1asqjmGIHyQsVc83Lu16mLhmV6vvvbE9pFCI7tVU/OXbE/KgDs2pEo4BE6Y5FbZXTMk7OmQ/ejrP28YyOQsWCOulxeALY6KjSp3vu1Z8wxtzxNIf6utUl3eWmQSv1N/Z9vOVm7tzLxDSR1a2gCFIwNJuPgV5rQ96MNMEKy8baa0Xus3Omfnlw0EeaAi7FgLEs06Th58VB3OCmaWvN3PP9c2zBGnRGli0KHThamxLbv1MN+rppr6LufE+V0zTqn0QoU+OBUFHGK4TjjiSSWkGi43cGqSK/ufwbtummx9AAVA6f0aDT4DiqSdV6vmhE2Cj7NkfF6Rck9VfrlCc8AgjQQ6bohMejCDHI78cjTBDegvNtJp8OtORKUQIon5HCUR2mrdC8B8snF4p0sqgr1E3TAMhqzew256Nd24Yf5q0kYVF2M4c3zD+bkwFvMoM4Eu0Mhg91/tF7GaAfuvZ/1YECBQ4hSaJBrsttW6Ie8hI2HCXykcCl3qI1/sag5D1yGX6ffNNTojoj1vj2F6islO6p+l1Dbg3Y2xqKOrwJ47y3MBM18FJ4C0rl6arFNU7xPISaZWDkD9urTh6qpYlbsoQ3+w9LP1+ofzTf1SfW4oIVHYFxAacppQub6DnjVBxuINHVJ8kGutGEDox+NXWrBL9m/M7g="

deploy:
  - provider: releases
    file_glob: true
    file: "y2jj2y-*windows*.zip"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = windows"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "y2jj2y-*darwin*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "y2jj2y-*linux*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    <<: *_github_api_key
...
